# Generated by Django 4.0.4 on 2022-06-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
